name: d100_project_movies_ds_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - lightgbm
  - pytest
  - fastparquet
  - category-encoders
  - dalex
  - shap
  - ipykernel
  - pre-commit
