name: d100_project_movies_ds_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - lightgbm
  - pip
  - pip:
      - pytest
      - fastparquet
      - category-encoders
      - dalex
      - shap
